#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
setxkbmap -option grp:alt_shift_toggle us,ru &

bspc monitor -d 1 2 3 4 5 # VI VII VIII IX X

bspc config focus_follows_pointer true

# running `xinput` commands to configure touchpad behaviour (probably should do this in some other file)
xinput set-prop 'ELAN06FA:00 04F3:31AD Touchpad' 'libinput Tapping Enabled' 1 &
xinput set-prop 'ELAN06FA:00 04F3:31AD Touchpad' 'libinput Natural Scrolling Enabled' 1 &
xinput set-prop 'ELAN06FA:00 04F3:31AD Touchpad' 'libinput Accel Speed' 0.4 &

# running `xbindkeys` in order to be able to change volume with functional keys
xbindkeys &

# running `nitrogen` in order to restore the background image (probably should replace this with `feh`)
nitrogen --restore &

# running polybar
bash ~/.config/polybar/launch.sh &

picom -f &

bspc config border_width 4
bspc config window_gap 20
bspc config focused_border_color "#989cff"
bspc config normal_border_color "#1f222b"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
