[font]
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
style = "Bold"

[colors]
draw_bold_text_with_bright_colors = true

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[cursor.style]
blinking = "Always"
shape = "Beam"

[window]
decorations = "none"
opacity = 0.9
padding = {x = 25, y = 25}
dynamic_title = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
